name: Google Internal Tests Enforcement

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: read
  statuses: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/google-internal-tests@fac5f7cd944a71f4680a1754164a5fd92e3b8866
        with:
          run-tests-guide-url: http://go/angular/g3sync
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # List must be manually kept in sync with google3/third_party/javascript/angular2/copy.bara.sky
          synced-files: |
            LICENSE
            modules/benchmarks/**
            modules/system.d.ts
            packages/**
          # List of patterns which are always considered external, even when matching above.
          always-external-files: |
            packages/*
            packages/bazel/*
            packages/bazel/src/*
            packages/bazel/src/api-extractor/**
            packages/bazel/src/builders/**
            packages/bazel/src/ng_module/**
            packages/bazel/src/ng_package/**
            packages/bazel/src/protractor/**
            packages/bazel/src/schematics/**
            packages/bazel/src/types_bundle/**
            packages/compiler-cli/src/ngcc/**
            packages/compiler-cli/linker/**
            packages/compiler-cli/ngcc/**
            packages/compiler-cli/src/ngtsc/sourcemaps/**
            packages/compiler-cli/private/bazel.ts
            packages/compiler-cli/private/localize.ts
            packages/compiler-cli/private/tooling.ts
            packages/compiler-cli/private/babel.d.ts
            packages/compiler-cli/src/bin/**
            packages/docs/**
            packages/elements/schematics/**
            packages/examples/**
            packages/language-service/**
            packages/localize/**
            packages/private/**
            packages/service-worker/**
            packages/common/locales/generate-locales-tool/**
            packages/common/locales/index.bzl
            packages/http/**
            **/.gitignore
            **/.gitkeep
            **/yarn.lock
            **/package.json
            **/third_party/**
            **/tsconfig-build.json
            **/tsconfig-tsec.json
            **/tsconfig.json
            **/rollup.config.js
            **/BUILD.bazel
            **/*.md
            packages/**/integrationtest/**
            packages/**/test/**
            packages/zone.js/*
            packages/zone.js/dist/**
            packages/zone.js/doc/**
            packages/zone.js/example/**
            packages/zone.js/scripts/**
