name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@c1eb5f77b2340f79119a55c412b795756625f136
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
